### ISSUE TITLE
Habitat crashes at login when using spaces in Username

### ISSUE THREAD

**Issue by The-Dhel** [frandallfarmer/neohabitat#114]
When you sign up for QLR using a username containing spaces (Tested with "The Dhel"), Habitat will refuse to login and continue loading after inserting the Imagery disk. The game is simply stuck at the Club Caribe screen. Creating a new username, using the name "Dhel", works fine and Habitat loads fine.

**Comment by frandallfarmer** [comment]
Fixed by @steve earlier today...
