### ISSUE TITLE
Chat text not showing different colors for different avatars

### ISSUE THREAD

**Issue by rickyderocher** [frandallfarmer/neohabitat#128]
All chat text is light green on my client - both mine and another avatar's. (It is working normal on his, I asked him about it)

He teleported into the room that I was in. (Don't know if this has anything to do with it)

This is the first time that I've observed this happening.

**Comment by rickyderocher** [comment]
[
![03](https://cloud.githubusercontent.com/assets/25597921/23575573/c7452434-005c-11e7-81e8-4ac782998c88.png)
](url)

**Comment by frandallfarmer** [comment]
This is possible with Habitat.
