### ISSUE TITLE
Nested Containers Broken

### ISSUE THREAD

**Issue by frandallfarmer** [frandallfarmer/neohabitat#13]
Attempting to load an Elko context (habitat region) that has an open container that contains an object breaks the NeoHabitat server as it tries to walk the container tree when initializing noids for the items.

Elko fix required: @fudco is on it.

Critical for launch.

**Comment by FUDCo** [comment]
This should be fixed in commit 2e6809b1b59c5c30dc06800bdf0eb4f5f75bb823 in the https://github.com/FUDCo/Elko master branch (presumably somebody with stronger git-fu than I can tell me how to properly link to it or provide a pull request to neohabitat or whatever the pattern is).

**Comment by frandallfarmer** [comment]
Merged and testing now.

**Comment by frandallfarmer** [comment]
Works end-to-end in latest Neohabitat build. Confirm in context-table.
