### ISSUE TITLE
Changing a vendo's display contents results in an error beep for other Avatars in region

### ISSUE THREAD

**Issue by ssalevan** [frandallfarmer/neohabitat#156]
**Description**
When a vendo's display item is changed by an Avatar, the error beep will sound for all other Avatars in a region.

**Reproducer**
1. Put at least two avatars in a room with a vendo
2. Have one avatar change the display item of the vendo

**Results**
Error beep heard alongside vendo change sound by all other Avatars in the region

**Expected Results**
No beep

**Comment by frandallfarmer** [comment]
Fixed and tested.

Thanks - there was a bad noid in the $POSTURE message and it was causing all kinds of havok. :-)
