### ISSUE TITLE
Launch Region Design

### ISSUE THREAD

**Issue by frandallfarmer** [frandallfarmer/neohabitat#17]
What are the launch regions going to be like?
I've been focused purely on aesthetics and core functionality.

Designing a few simple regions that look entertaining and would make for great demo/screen shots for launch would be awesome. Ideas? Volunteers? We have the GOD TOOL to use to help fiddle around with layout.

Perhaps recreating one or to of the old regions from videos?

**Comment by StuBlad** [comment]
I'd actually been looking into recreating some of the old regions from the griddle files in the Habitat source. Ran into some issues though with regards to certain classes not being currently available (Trapezoid being one of the major blockers). I think it'd be great for nostalgia purposes though!

**Comment by frandallfarmer** [comment]
Let's prioritize those classes @stublad. Please mark the wiki page with the list.

**Comment by frandallfarmer** [comment]
Demo launch regions complete.
