### ISSUE TITLE
MOTD is displayed more than once per session

### ISSUE THREAD

**Issue by kelkin** [frandallfarmer/neohabitat#188]
When leaving your avatar idle for a few minutes (amount not identified yet), when you move to the next region, the MOTD is displayed again as if there is an idle timeout disconnecting the session, and then the movement re-connecting the session fooling the server into thinking it's a brand new session rather than a re-connected session.

**Comment by kelkin** [comment]
![motd_repeat](https://cloud.githubusercontent.com/assets/16828241/26334064/524971cc-3f30-11e7-8589-a541ee1a66fc.jpg)

**Comment by frandallfarmer** [comment]
Fixed with the latest.
