### ISSUE TITLE
Wishlist - MADE-Based Cover Screen?

### ISSUE THREAD

**Issue by frandallfarmer** [frandallfarmer/neohabitat#19]
Any chance we could get this image adapted and patched-in to be the launch screen for the C64 client? As I recall the bits for the cover screen are uncompressed in order in the binary (and vanish when overwritten by the first region arriving.) The surrounding area would have to be perfect black to mask the shooting-star, but if this works it might be cool.
 
![image](https://cloud.githubusercontent.com/assets/314896/22120877/71c26faa-de36-11e6-89f2-78399dad2d9a.png)

Alex - what do you think about this idea?

**Comment by StuBlad** [comment]
![titlescreen](https://user-images.githubusercontent.com/25211663/29196604-56529d34-7e2d-11e7-830d-815b9ff08f07.png)

Can we close this issue now? 😄

**Comment by frandallfarmer** [comment]
Done! Thanks all!
