### ISSUE TITLE
Lamps in turfs should be defaulted to being on

### ISSUE THREAD

**Issue by TheCarlSaganExpress** [frandallfarmer/neohabitat#205]
Within the turfs, the lamps are off and the rooms are lit. This means that the rooms can never be dark.
To fix this, lamps in all turfs should be defaulted to being on.
An example of this issue would be in Hyper Dr #730.

**Comment by frandallfarmer** [comment]
This is a simple global database change - someone who is skilled at sed can do this. :-)

**Comment by frandallfarmer** [comment]
I miss ghu.

**Comment by StuBlad** [comment]
I wish we had a ghu equivalent!
