### ISSUE TITLE
Pressing F1 to unghost or ghost prior to the previos request completing, hangs the client.

### ISSUE THREAD

**Issue by kelkin** [frandallfarmer/neohabitat#208]
When unghsoting, if you try to ghost too quickly (prior to your unghost request completing), your client will hang.

**Comment by frandallfarmer** [comment]
All the ghost related bugs are due to the same overarching bug...

**Comment by frandallfarmer** [comment]
Workaround in place - a dialog tells users to wait. Closing as a duplicate of the command race bug.
