### ISSUE TITLE
Aquariums are not glued + Other things you should not be able to steal

### ISSUE THREAD

**Issue by TheCarlSaganExpress** [frandallfarmer/neohabitat#210]
Aquariums need to be glued inside the houses. Also, if you put an aquarium inside a cabinet you cannot move it and it says-
"You are not the shopkeeper. You cannot pick this item up."
This occurred in Hyper Dr #930.

Flower vases are not glued to turfs and can be picked up. This occurred in Hyper Dr #830.
This relates to issue #194.

![stealing fish](https://cloud.githubusercontent.com/assets/7967050/26613351/4cf996c6-4588-11e7-8b3d-985da73c00e1.JPG)

**Comment by frandallfarmer** [comment]
Look what I found in the source:
    if (/* TODO DisplayCase dcont.locked(self.position+1)&dcont.owner */ "" != avatar_userid) {

**Comment by frandallfarmer** [comment]
I'll fix all immobile containers in turfs to be restricted to the owner only - not just display cases.
