### ISSUE TITLE
Paper from a vendo can lock the client

### ISSUE THREAD

**Issue by TheCarlSaganExpress** [frandallfarmer/neohabitat#220]
When pressing "DO" on a piece of paper that is purchased from a vendo it will lock/crash the client.
This happened in Downtown_7b on the demo server.

**Comment by frandallfarmer** [comment]
Let's not put paper in vendos - paper is free in your pocket.
Books should be in vendos.

**Comment by TheCarlSaganExpress** [comment]
Turns out I made a mistake and it was actually a book, rather than paper. 
See #254
