### ISSUE TITLE
Teleporter/Token splitting crash

### ISSUE THREAD

**Issue by StuBlad** [frandallfarmer/neohabitat#233]
![crash](https://cloud.githubusercontent.com/assets/25211663/26745433/6b5dc068-47e2-11e7-94d2-3b281fd4da2a.png)

This happened when user Rachy was attempting to split tokens in a teleporter. Once she had confirmed the amount to split, I got a Fatal Error 7. She did not crash from the world.

**Comment by frandallfarmer** [comment]
Token PUT in teleporter was producing FE7 until the lastest build - you should be able to see other's activate a teleport without crashing now. I'm assuming this is what this is, so I'm closing it as fixed for now.
