### ISSUE TITLE
F8: Tips

### ISSUE THREAD

**Issue by frandallfarmer** [frandallfarmer/neohabitat#240]
After watching a lot of people play, and the the BobbyBlackWolf stream, it became clear that we need some in-world tips. I was thinking to attach these to F8 (and then changing the MOTD to include "press f8 for tips") One tip would appear per key press.

What tips do you think we should have? What are the things that are tripping new users up?

"Habitat is better with a joystick."
"F7 is object HELP. Move your cursor to an object and press it for more details."
"F7 while pointing at the ground often gives helpful navigational information."
"Yes, you can customize your avatar with body paint and different heads. Visit the stores on Rodeo Drive."
"There is a sex-change machine in the backroom of Kelly's"
"You can teleport to your turf by entering "home" in any active teleporter."
"Teleporters, like other things in Habitat, require you to PUT tokens in them to activate."
"Elevators don't require tokens, just WALK to them, and type the floor number while your cursor is pointing at it. Enter "lobby" to get to the 0th floor."
"People sometimes congregate on the roof of the  Popustop apartment complex."

What else? Please add as comments to this issue.

**Comment by frandallfarmer** [comment]
"Visit http://neohabitat.org to find the detailed Avatar Handook."

**Comment by TheCarlSaganExpress** [comment]
I came up with a few tips that should help players get around a bit easier.

"Some machines may require your avatar to be positioned a certain way for it to work. Make sure to first aim your cursor at the machine and perform a GO command."
"Need tokens? Stop by an ATM and GET some more."
"Pressing F3 will tell you who is currently online."
"Type in 'pop-42nd' or 'pop-plaza' in a teleporter if you want to get back to the city."

**Comment by frandallfarmer** [comment]
This is "done" as in working. If you think there's some more things to add - just check them in!
