### ISSUE TITLE
Stuck loading a specific region in The Woods

### ISSUE THREAD

**Issue by isani** [frandallfarmer/neohabitat#244]
Steps to reproduce:

1. Walk along Woods Road until you reach the sign for "Rhondas".
2. Go down. There should be a trash can and a sign that reads "Keep off".
3. Go down.

The client will hang indefinitely while the loading music plays.

Alternatively, you can go to the region with the trash can and go right-down-left with the same result.

**Comment by StuBlad** [comment]
Just leaving a note here that the region in question is Woods_7g

**Comment by frandallfarmer** [comment]
Can we close this as fixed?
