### ISSUE TITLE
dialog partners will get same bubble color easily

### ISSUE THREAD

**Issue by Flexmaen** [frandallfarmer/neohabitat#246]
Something that happens quite often is, that both characters of the conversation will get the same color for their bubbles. Initially colors seems to be different, but suddenly (maybe if someone changed the room) the whole conversation of both will be in light green. (In both ESP and in normal conversation). Not a big thing, but maybe something that's not ment to be like this.

![herpes3](https://user-images.githubusercontent.com/6330276/27142141-784e1a56-512a-11e7-8379-3b4227b0ca8e.png)

**Comment by frandallfarmer** [comment]
Avatars can end up with the same mode for color determination. Closing as "legacy problem"
