### ISSUE TITLE
can't sit on a chair when placing an object inside

### ISSUE THREAD

**Issue by Flexmaen** [frandallfarmer/neohabitat#249]
I put a mail into a chair (put on chair).
Then when I click "go" on the chair several times I can't sit there anymore.

Might make sense in case of bigger objects, otherwise I don't think this is ment to be like this, so I report it.

**Comment by frandallfarmer** [comment]
Habitat containers are "slot" based. Chairs have one slot - it holds an item or a sitting avatar.

This is as designed.
