### ISSUE TITLE
BUG: F7 on paper where the first line is blank doesn't display help text

### ISSUE THREAD

**Issue by StuBlad** [frandallfarmer/neohabitat#341]
If you issue an F7 on a piece of paper where the first line is blank, the paper HELP text will not display or the preview of the papers text.

For example, here is a screenshot of me performing this action on a note where the text started on line 2:

![image](https://user-images.githubusercontent.com/25211663/38785517-e80bfba4-4118-11e8-8ce9-3394da9c4296.png)

In Habitat originally, issuing F7 on Paper would show this:

![image](https://user-images.githubusercontent.com/25211663/38785532-f8b4d912-4118-11e8-991d-6397bb6f94d4.png)

This still works if text begins on the first line.

It's not currently clear how Habitat would've handled this particular case but the code will tell whether if it found the first line of actual text and used that to display.

**Comment by StuBlad** [comment]
https://github.com/Museum-of-Art-and-Digital-Entertainment/habitat/blob/b59e2520fd8690bf99a1db43928a679f2fbc875c/sources/stratus/Classes/class_book.pl1#L72

Is a link to the code that handles this particular action.

**Comment by StuBlad** [comment]
Based on the original code mentioned in my previous comment, it appears to use the following command to trim the blank space on the paper until it reaches a character:

`nice_title = ltrim(rtrim(title));`

For books and books in vendos, if there is no "title" then it will let you know that book has no title, but for paper, if there is nothing on the paper it won't say anything other than "This paper begins ."

In our current code, this isn't handled the same as the original server and so we just get a blank speech bubble.

**Comment by frandallfarmer** [comment]
FIxed - now matches orginal PL/1 behavior.

![image](https://github.com/user-attachments/assets/dec3eb17-9eb8-452e-86b7-04dbcf35334d)
