### ISSUE TITLE
stuck at press alt-n

### ISSUE THREAD

**Issue by Titanor-Soulstone** [frandallfarmer/neohabitat#350]
hey there
i am currently having trouble getting neo habitat to run on retropie os
it is saying press alt-n but when i press it the message appears again
i dont know if this is a problem with the raspberry pi or a problem with neo habitat, so yeah

**Comment by StuBlad** [comment]
If the message appears a second time it means that VICE hasn't switched to the B disk yet. If it has, you should see it say "Version 1.0". I don't think any of us on the team have tried to get it running on retropie yet. I'd recommend joining our Slack to discuss troubleshooting further though. You can access it here: http://slack.neohabitat.org/

**Comment by frandallfarmer** [comment]
That message is for the installer versions only, as those come with a preconfigured VICE instance. If you are using your own, you'll need to manually switch to the data disk using the Vice menus.
