### ISSUE TITLE
Defer QLR binding to NeoHabitat

### ISSUE THREAD

**Issue by frandallfarmer** [frandallfarmer/neohabitat#42]
QLR connects to Neohabitat (bridge) the instant a user connects to QLR - it would help development a bit if the connection to Neohabitat was delayed until the 'Club Caribe' game application was selected by the client user. This would allow a developer to bounce the Bridge/Neohabitat server as part of a development cycle while the QLink client is connected only to QLink (in People connection, or wherever.)

This is not a priority.

**Comment by frandallfarmer** [comment]
It would also need to break that connection whenever a user returned to People Connection from Habitat.

**Comment by ssalevan** [comment]
This behavior is now implemented in QLR.
