### ISSUE TITLE
The program gets stuck at the [DO] command (token in hand, used on door)

### ISSUE THREAD

**Issue by radius75** [frandallfarmer/neohabitat#431]
Vice3.7.1

- take the token out of your pocket and DO on the door
![vice-screen-2023070912521390](https://github.com/frandallfarmer/neohabitat/assets/1929111/a9f79754-7246-4e34-a14e-a95301a3c61c)

**Comment by frandallfarmer** [comment]
OOh! This looks like a real bug! I'll look at it soon.

**Comment by frandallfarmer** [comment]
I'm having problems duplicating this bug. Are you certain you were pointing at the door instead of your avatar or the coin? I noticed that your hand is out... @radius75

**Comment by radius75** [comment]
I've blocked myself a few times this way. Both on Windows 7 GTKVice3.7.1 and also on Vice in a web browser.
Avatar holds this token/coin, door is closed, command DO.

**Comment by radius75** [comment]
- run game
- PUT token on Teleport
- typing "home"
- use DO on the door (token in hand)

I used DO 3x on the door and got stuck.
I just did this right now via GTKVice3.7.1
Looks like I've lost connection to the server.

**Comment by radius75** [comment]
I also checked on real C64 with Wi-FiStrikelink modem.
There is the same problem.

Strikelink set: at$sb=1200, at&k0, at&w
Habitat-Boot_v1.1-modemenabled.d64
atdthabitat.themade.org:1986

**Comment by radius75** [comment]
![obraz](https://github.com/frandallfarmer/neohabitat/assets/1929111/58b169b1-a9ae-40e5-ac7e-67e339332ae6)
after all these tests on Web, Vice and Real C64, I am duplicated 3x in Home :D

**Comment by frandallfarmer** [comment]
Thank you for the detailed duplication steps.

I did notice something unfamiliar: "atdthabitat.themade.org" - that URL the 'atdthabitat' is odd (I recall what ATDT was from modem days, but when did that subdomain become active. Certainly this isn't the source of the bug, but I'm curious...

**Comment by frandallfarmer** [comment]
Testing with my local server and following those exact steps the door is working normally. I do have one question though:

"I used DO 3x on the door and got stuck."

What exactly do you mean by "Do 3x"? are you issuing the commands fast or slow? Next up I'll try production (habitat.made.org).

**Comment by frandallfarmer** [comment]
I tried with app.neohabitat.org aka habitat.themade.org also functions properly for me.  I spammed DO on the door in my turf while holding a token a dozen times, and they all worked.

We'll probably need to look at the logs when you are failing @radius75.

There are so many layers of performance emulation going on, I'm at a bit of a loss without seeing both ends in action.

**Comment by frandallfarmer** [comment]
Perhaps there's a LAG effect that I'm not seeing because I'm close to the server? Where are you pinging in from @radius75 ?

**Comment by frandallfarmer** [comment]
.... Maybe Poland (your profile here) ... I'm betting that has something to do with it. Any chance you could run a local server (Linux or WSL2) @radius75 ? That would eliminate that variable.

Lag is definitely an enemy of Habitat - back in the 1980s this was only used in the USA - and if connection-lag got real bad the low-level protocol was known for failing. Since you're getting the same issue repeatedly, I'm not 100% sure that is it. Or, perhaps, this particular sequence is sensitive to delays? 

I'm keeping this open until we know it's related to lag.

**Comment by radius75** [comment]
> Thank you for the detailed duplication steps.
> 
> I did notice something unfamiliar: "atdthabitat.themade.org" - that URL the 'atdthabitat' is odd (I recall what ATDT was from modem days, but when did that subdomain become active. Certainly this isn't the source of the bug, but I'm curious...

I am using atdt to connect to the server.
(both in Vice +tcpser.exe as a UserPort modem and in a real C64 with a StrikelinkWiFi modem) I enter this command with the address in the terminal in the game. (F7) Habitat-Boot_v1.1-modemenabled.d64

> Testing with my local server and following those exact steps the door is working normally. I do have one question though:
> 
> "I used DO 3x on the door and got stuck."
> 
> What exactly do you mean by "Do 3x"? are you issuing the commands fast or slow? Next up I'll try production (habitat.made.org).

I use DO and wait for the door to open or close, after a ball of tries the game locks up when trying to DO.
The door does not open/close and DO is displayed all the time.
Looks like a server connection error.


> Perhaps there's a LAG effect that I'm not seeing because I'm close to the server? Where are you pinging in from @radius75 ?

Yes, Poland.

> 

I only use Win7 and unfortunately I don't have the possibility to run such a server at my place.
I am unable to PING or TRACERT to address 20.3.249.92. This is probably the current address of the Neohabitat server?
Ping does not respond and tracert does not complete.
It may be as you say, some packet with a response or a request to the server gets lost somewhere along the way and the game freezes in an infinite wait.

**Comment by frandallfarmer** [comment]
I presently don't have access to the server log at habitat.themade.org.

I don't understand "after a ball of tries the game locks up when trying to DO." - What happens the first time you try to DO the door after it opens/closes? I'm surprised you would even get another chance to try.

Note: When you are carrying a coin and you DO on yourself or the coin a coin-splitting text-prompt will appear in the chat-entry area - just in case that is happening.

Please try this - login and carry the coin. DO on the door and wait for the animation/sound to complete. Walk to another place in the room (does that work?) If that works, walk back to the door (don't point to the black space in an open door...) and DO it again. Please report the result.

Don't multi-try anything before getting confirmation from the server. That won't work for sure.

**Comment by radius75** [comment]
I tried to record a video. But just today (in the morning) the error, despite several attempts, could not be reproduced.
At some point it stopped on GO, I waited and then I started pressing F1-F7 but after a while it went on.
Anyway, I'm providing the link. You will see how I proceed. (74MB .mkv video file)
https://mega.nz/file/fJwSQJoL#KBdfydrv7WXbvLKT_0jQG8cH7UqRElE_7LOschY6JTE

**Comment by radius75** [comment]
What you see as "DO" three times quickly on the door is not me. It's a bug because my character duplicated three times, a game bug.
I only did "DO" once and the game did it three times.
In the later part of the video, they go to an empty house and there you can see how it works normally.
But yes, despite these errors, the connection was very very stable.

**Comment by frandallfarmer** [comment]
If you would, @radius75 - please open an issue with "multiple connections from the same avatar" as a bug issue.

THAT's a real problem. Also note that it may be related to issues #419 and #393 - we don't hang up some connections because of a work-around for a disconnect bug.
