### ISSUE TITLE
Spray_can

### ISSUE THREAD

**Issue by frandallfarmer** [frandallfarmer/neohabitat#77]
This is the method to change the color/patterns on things, including the avatar and the avatar's head... A good starter task.

**Comment by ssalevan** [comment]
I'll claim this one.

**Comment by ssalevan** [comment]
Implemented; closing as Complete.

**Comment by frandallfarmer** [comment]
The latest push contains fully functional (minus self-delete) spray cans. This is a pretty good reference class for seeing how stateful objects work.
![screenshot 2017-02-10 09 55 47](https://cloud.githubusercontent.com/assets/314896/22837925/88c34d80-ef77-11e6-9684-c61558f91a64.png)
