### ISSUE TITLE
Compass

### ISSUE THREAD

**Issue by frandallfarmer** [frandallfarmer/neohabitat#78]
A great starter class - the compass always points to the West pole.

**Comment by frandallfarmer** [comment]
It'd be nice if one of these, working, were in the avatar's pocket for GDC.

**Comment by ssalevan** [comment]
This change has been implemented and deployed; closing as Resolved.

**Comment by frandallfarmer** [comment]
There's a bug in that the die always rolls a 1. Jason's on it.
This is a class not used by GDC, so we're going to use this as a tool for establishing his dev environment.

**Comment by keiyakins** [comment]
Is it the die that's broken or the compass?

**Comment by frandallfarmer** [comment]
OOPS! Thanks for catching that @keiyakins!
