### ISSUE TITLE
Need 'Jump' feature added to God tool

### ISSUE THREAD

**Issue by kelkin** [frandallfarmer/neohabitat#84]
I'm requesting a feature be added to the God tool which allows you to navigate directly to a context by context-name. This will assist with region development and linking.

**Comment by frandallfarmer** [comment]
Implementation plan: add "jCONTEXTNAME" to GODTool magic type. Might be a little tricky dealing with the client being in GOD mode when executing the command, and I'm not sure forced region changes are implemented properly yet.

**Comment by frandallfarmer** [comment]
This command is implemented. Some notes:
1) The godtool command is jCONTEXTNAME, if you leave off the "context-" it's ok. This is a valid jump command: jtest, jturf, jback4t_41 all work
2) NOTE, the _ character will appear as a squigly vertical bar. That's what I get when I enter the _ charcater on VICE. It maps to 127 ascii, which JS/Java think is '{' and that is what you'll see in the logs.  I translate all { to _ before attempting to change regions.
3) IMPORTANT: THERE IS NO ERROR HANDLING. BE 100% SURE OF YOUR COMMAND BEFORE YOU SEND IT. YOU WILL HANG IF THE REGION DOES NOT EXIST.
