### ISSUE TITLE
Construction Tape for GDC

### ISSUE THREAD

**Issue by frandallfarmer** [frandallfarmer/neohabitat#95]
Anyone want to take a stab at making Under Construction tape Super_trapezoid? 4x8 bytes of texture... Cool super-trap shapes that look like tap across the incomplete region.

![image](https://cloud.githubusercontent.com/assets/314896/23051902/7f757050-f481-11e6-9f03-ab9d0f9942e4.png)

![image](https://cloud.githubusercontent.com/assets/314896/23051933/c337aca4-f481-11e6-8bc9-2bc16f458946.png)

**Comment by frandallfarmer** [comment]
Even just the diagonal stripe design would be super cool.

**Comment by keiyakins** [comment]
I have a diagonal stripe pattern I've shown in slack, how do you want it 'delivered'? A simple test region? Loose item definition?

**Comment by frandallfarmer** [comment]
Please work with Keith to put it creatively in a "missing region" region.
Also, please work up a version with SKIN color where WILD is in the pattern. We can use that anywhere!

**Comment by kelkin** [comment]
Keiyakins, would love to see what you have done. Please DM me in Slack. Thanks!

**Comment by frandallfarmer** [comment]
This is in.
